// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTxudDXZykLD8OyYH0gOjGLalJhS1LNE',
    appId: '1:244594581534:web:f240e6b3e0fc013d254e0f',
    messagingSenderId: '244594581534',
    projectId: 'authentication-fb86e',
    authDomain: 'authentication-fb86e.firebaseapp.com',
    storageBucket: 'authentication-fb86e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuvszEgBIl-aPthCzBSHpIi6ytPB1LW4g',
    appId: '1:244594581534:android:63187906868b798f254e0f',
    messagingSenderId: '244594581534',
    projectId: 'authentication-fb86e',
    storageBucket: 'authentication-fb86e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC4jCZKYxFHs_nTB_80JiSxxqnw3Lh3fo',
    appId: '1:244594581534:ios:6c35bbfe5ceeb3ae254e0f',
    messagingSenderId: '244594581534',
    projectId: 'authentication-fb86e',
    storageBucket: 'authentication-fb86e.appspot.com',
    iosBundleId: 'com.example.authentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC4jCZKYxFHs_nTB_80JiSxxqnw3Lh3fo',
    appId: '1:244594581534:ios:6c35bbfe5ceeb3ae254e0f',
    messagingSenderId: '244594581534',
    projectId: 'authentication-fb86e',
    storageBucket: 'authentication-fb86e.appspot.com',
    iosBundleId: 'com.example.authentification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChTxudDXZykLD8OyYH0gOjGLalJhS1LNE',
    appId: '1:244594581534:web:63f40a29a3a7ae58254e0f',
    messagingSenderId: '244594581534',
    projectId: 'authentication-fb86e',
    authDomain: 'authentication-fb86e.firebaseapp.com',
    storageBucket: 'authentication-fb86e.appspot.com',
  );
}
